// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/recipe-app/Capture.tsx": () => import("../components/mockups/recipe-app/Capture.tsx"),
  "./components/mockups/recipe-app/Preferences.tsx": () => import("../components/mockups/recipe-app/Preferences.tsx"),
  "./components/mockups/recipe-app/Results.tsx": () => import("../components/mockups/recipe-app/Results.tsx")
};
